import type { Scanner, ScanContext } from '../contracts';
import { CHECK_IDS } from '../contracts';
import { provenanceFromExchange } from '../evidence-provenance';
import { getHomepageHtml } from './shared';
import { extractPageSignals, type LegalClass } from '../util/html';
import { truncate } from '../util/hash';

export const PRIVACY_SCANNER_VERSION = '1.0.0';

const SCANNER_ID = 'privacy.pages';

const TRACKED_CLASSES: LegalClass[] = ['privacy', 'terms', 'legal', 'contact', 'accessibility'];

export const privacyPagesScanner: Scanner = {
  id: SCANNER_ID,
  version: PRIVACY_SCANNER_VERSION,
  description:
    'Public privacy / legal / terms / contact / accessibility page indicators in the delivered homepage HTML, plus reachability of the privacy page and consent-tool indicators.',
  async run(ctx: ScanContext): Promise<void> {
    const home = await getHomepageHtml(ctx);
    const base = home.exchange.finalUrl;

    if (home.html === null) {
      const state = home.reason === 'error' ? 'ERROR' : 'NOT_CHECKED';
      ctx.evidence.add({
        scannerId: SCANNER_ID,
        scannerVersion: PRIVACY_SCANNER_VERSION,
        checkId: CHECK_IDS.privacyLinkScan,
        kind: 'page.presence',
        state,
        subject: base,
        method: 'html-scan',
        data: { reason: home.reason, contentType: home.contentType },
        provenance: provenanceFromExchange(home.exchange),
        limitations: ['The homepage HTML could not be scanned, so no page-presence claim is made.'],
      });
      ctx.evidence.add({
        scannerId: SCANNER_ID,
        scannerVersion: PRIVACY_SCANNER_VERSION,
        checkId: CHECK_IDS.consentIndicator,
        kind: 'page.presence',
        state,
        subject: 'consent-indicators',
        method: 'html-scan',
        data: { reason: home.reason },
        provenance: provenanceFromExchange(home.exchange),
        limitations: ['The homepage HTML could not be scanned, so no consent indicator claim is made.'],
      });
      return;
    }

    const signals = extractPageSignals(home.html, base);
    const legalLinks = signals.links.filter((link) => link.legalClass !== null);
    const provenance = provenanceFromExchange(home.exchange);

    ctx.evidence.add({
      scannerId: SCANNER_ID,
      scannerVersion: PRIVACY_SCANNER_VERSION,
      checkId: CHECK_IDS.privacyLinkScan,
      kind: 'page.presence',
      state: 'OBSERVED',
      subject: base,
      method: 'html-scan',
      data: {
        totalLinks: signals.links.length,
        internalLinks: signals.links.filter((link) => link.kind === 'internal').length,
        externalLinks: signals.links.filter((link) => link.kind === 'external').length,
        legalLinks: legalLinks.slice(0, 25).map((link) => ({
          class: link.legalClass,
          url: link.resolved,
          text: link.text,
        })),
      },
      provenance,
      limitations: [
        'Link extraction uses pattern matching over the delivered HTML; navigation generated by JavaScript after page load is not visible to this check.',
      ],
    });

    for (const cls of TRACKED_CLASSES) {
      const matches = legalLinks.filter((link) => link.legalClass === cls);
      ctx.evidence.add({
        scannerId: SCANNER_ID,
        scannerVersion: PRIVACY_SCANNER_VERSION,
        checkId: CHECK_IDS.privacyLinkPresence(cls),
        kind: 'page.presence',
        state: 'OBSERVED',
        subject: `link:${cls}`,
        method: 'html-scan',
        data: {
          class: cls,
          found: matches.length > 0,
          count: matches.length,
          urls: matches.slice(0, 5).map((link) => link.resolved),
        },
        provenance,
        limitations: [
          'Presence is judged from the delivered homepage HTML only; pages linked from subpages or menus rendered later are not seen.',
        ],
      });
    }

    const privacyLink = legalLinks.find((link) => link.legalClass === 'privacy' && link.resolved !== null);
    if (privacyLink?.resolved) {
      const page = await ctx.http.request(privacyLink.resolved, { method: 'GET' });
      const pageSignals = page.bodyText === undefined ? null : extractPageSignals(page.bodyText, page.finalUrl);
      ctx.evidence.add({
        scannerId: SCANNER_ID,
        scannerVersion: PRIVACY_SCANNER_VERSION,
        checkId: CHECK_IDS.privacyPageReachability,
        kind: 'page.reachability',
        state: page.error !== undefined ? 'ERROR' : 'OBSERVED',
        subject: privacyLink.resolved,
        method: 'GET',
        data: {
          url: privacyLink.resolved,
          finalUrl: page.finalUrl,
          status: page.status,
          title: pageSignals?.title ?? null,
          error: page.error === undefined ? null : { code: page.error.code, message: page.error.message },
        },
        provenance: provenanceFromExchange(page),
        limitations: ['One request to the first privacy link found in the homepage navigation.'],
      });
    }

    ctx.evidence.add({
      scannerId: SCANNER_ID,
      scannerVersion: PRIVACY_SCANNER_VERSION,
      checkId: CHECK_IDS.consentIndicator,
      kind: 'page.presence',
      state: 'OBSERVED',
      subject: 'consent-indicators',
      method: 'html-scan',
      data: {
        detectedTools: signals.consentTools,
        hasCookieWord: signals.hasCookieWord,
      },
      provenance,
      limitations: [
        'Indicators are common consent-management product names found in the delivered HTML. A site can handle consent without using any of them.',
        'This is an indicator check, not an assessment of consent behaviour or legal compliance.',
      ],
    });
  },
};

export function truncateTitle(value: string | null): string | null {
  return value === null ? null : truncate(value, 160);
}
