packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/unenv-preset@2.16.2'
  - '@cloudflare/workers-types@5.20260922.1'
  - miniflare@5.20260921.0-alpha
  - wrangler@4.136.2
